#!/bin/bash
set -e

source $(dirname $0)/version

ARCH=${ARCH:-"amd64"}
SUFFIX=""
[ "${ARCH}" != "amd64" ] && SUFFIX="_${ARCH}"

cd $(dirname $0)/../package

TAG=${TAG:-${VERSION}${SUFFIX}}
REPO=${REPO:-rancher}

if echo $TAG | grep -q dirty; then
    TAG=dev
fi

cp ../bin/migration-tools .

IMAGE=${REPO}/migration-tools:${TAG}
docker build -t ${IMAGE} .
docker login --help
echo "${DOCKER_PASSWORD}" | docker login --username="${DOCKER_USERNAME}" --password-stdin "${REPO}"
docker push ${IMAGE}
echo ${IMAGE} > ../dist/images
echo Built ${IMAGE}
