name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
env:
  REPO: registry.cn-hangzhou.aliyuncs.com/hungzh
  TAG: dev
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build the Docker image
      run: make
      
    - name: Docker Login
      uses: docker/login-action@v2.2.0
      with:
        registry: ${{ env.REPO }}
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        
    - name: Docker Push
      uses: ${{ env.REPO }}/migration-tools:${{ env.TAG }}
